# Generated by Django 5.1.1 on 2024-09-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0003_rename_rating_count_book_rating_counts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating_counts',
            new_name='ratings_count',
        ),
    ]
