# Generated by Django 5.1.1 on 2024-09-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0006_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_name'], name='author_name_idx'),
        ),
    ]
