# Generated by Django 5.1.1 on 2024-09-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0011_remove_author_average_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('author_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_id', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('book_id', 'shelf_name', 'shelf_count')},
        ),
    ]
