# Generated by Django 5.1.1 on 2024-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
