# Generated by Django 5.1.1 on 2024-09-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0002_remove_customuser_cover_photo_author_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating_count',
            new_name='rating_counts',
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
