# Generated by Django 5.1.1 on 2024-09-21 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0004_rename_rating_counts_book_ratings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('author_id', models.IntegerField(default=-1)),
                ('shelf_name', models.CharField(blank=True, default='', max_length=100)),
                ('shelf_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['book_id'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book_id']},
        ),
    ]
