# Generated by Django 5.1.1 on 2024-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0005_bookshelf_favoritebooks_delete_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['author_id'], name='author_id_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['description'], name='description_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_id'], name='book_id_idx'),
        ),
        migrations.AddIndex(
            model_name='bookshelf',
            index=models.Index(fields=['book_id'], name='book_id_idx2'),
        ),
        migrations.AddIndex(
            model_name='bookshelf',
            index=models.Index(fields=['shelf_name'], name='shelf_name_idx'),
        ),
    ]
