# Generated by Django 5.1.1 on 2024-09-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0007_book_title_idx_book_author_name_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebooks',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='favoritebooks',
            name='title',
        ),
        migrations.AlterField(
            model_name='favoritebooks',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
