# Generated by Django 5.1.1 on 2024-09-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0010_alter_author_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='average_rating',
        ),
    ]
