# Generated by Django 5.1.1 on 2024-09-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recommender', '0012_alter_author_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='data_source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='fans_count',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
